#!/bin/sh

# sh-sourceable Environment file for compatibility
#
# This file fixes the variables responsible for making the XDG basedir spec work
# (https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)
# and does not set any other environment variables, as it is rather cumbersome
# to adopt changes herein. Other environment variables are set in the shell
# scripts' respective startup files (.zprofile, .bash_profile, ...).

# XDG base directory specification (XDG_{LIB,LOG}_HOME are not standard!)
export XDG_CACHE_HOME="${HOME}/.local/var/cache"
export XDG_CONFIG_HOME="${HOME}/.local/etc"
export XDG_DATA_HOME="${HOME}/.local/var/lib"
export XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-${HOME}/.local/run}"
export XDG_LIB_HOME="${HOME}/.local/lib"
export XDG_LOG_HOME="${HOME}/.local/var/log"
export LD_LIBRARY_PATH="${XDG_LIB_HOME}:${LD_LIBRARY_PATH}"

# Fix various applications to respect XDG
export GTK2_RC_FILES="${XDG_CONFIG_HOME}/gtk-2.0/gtkrc-2.0"
export GTK_RC_FILES="${XDG_CONFIG_HOME}/gtk-1.0/gtkrc"
export RANDFILE="${XDG_CACHE_HOME}/rnd"
export RXVT_SOCKET="${XDG_RUNTIME_DIR}/urxvtd.sock"
export TMUX_TMPDIR="${XDG_RUNTIME_DIR}"
export ZDOTDIR="${XDG_CONFIG_HOME}/zsh/default"

# Other session-wide variables
export SSH_AUTH_SOCK="${XDG_RUNTIME_DIR}/ssh-agent-${USER}-socket"
