" Vim main configuration file
"
" (C) 2016 - Roosembert Palacios <roosembert.palacios@epfl.ch>
" Released under CC BY-NC-SA License: https://creativecommons.org/licenses/
" TODO: Consider changing licence to Apache2
scriptencoding utf-8
set encoding=utf-8

" NeoBundle Scripts {{{
if has('vim_starting')
  if &compatible
    set nocompatible               " Be iMproved
  endif

  " Required:
  set runtimepath+=~/.vim/bundle/neobundle.vim/
endif

" Required:
call neobundle#begin(expand('~/.vim/bundle'))

" Let NeoBundle manage NeoBundle
" Required:
NeoBundleFetch 'Shougo/neobundle.vim'

NeoBundle 'scrooloose/nerdtree'
NeoBundle 'Lokaltog/vim-easymotion'
NeoBundle 'vim-scripts/Align'
NeoBundle 'sjl/gundo.vim'
NeoBundle 'shawncplus/skittles_berry'
NeoBundle 'mileszs/ack.vim'
NeoBundle 'benatkin/vim-move-between-tabs'
NeoBundle 'tpope/vim-fugitive'
NeoBundle 'tpope/vim-tbone'

NeoBundle 'shougo/vinarise'
NeoBundle 'Shougo/unite.vim'
NeoBundle 'Shougo/neomru.vim'
NeoBundle 'Shougo/vimproc',
	\ {
		\ 'build' : {
			\ 'windows' : 'make -f make_mingw32.mak',
			\ 'cygwin' : 'make -f make_cygwin.mak',
			\ 'mac' : 'make -f make_mac.mak',
			\ 'unix' : 'make -f make_unix.mak',
		\ },
	\ }
if has('lua')
	NeoBundle 'Shougo/neoinclude.vim'
endif

NeoBundle 'tsukkee/unite-tag.git'

NeoBundle 'chrisbra/vim-diff-enhanced'
NeoBundle 'haya14busa/incsearch.vim'
NeoBundle 'nathanaelkane/vim-indent-guides'

" NeoBundle 'Valloric/YouCompleteMe'
" NeoBundle 'powerline/powerline'
" NeoBundleLazy 'jeaye/color_coded'

" always show the status line.
" FIXME: Powerline?
set laststatus=2

" You can specify revision/branch/tag.
" FIXME: Added by Neobundle script on genesis, is it a good idea to fix the revision?
NeoBundle 'Shougo/vimshell', { 'rev' : '3787e5' }

" Required:
call neobundle#end()

" Required:
filetype plugin indent on

" If there are uninstalled bundles found on startup,
" this will conveniently prompt you to install them.
NeoBundleCheck
" }}} End NeoBundle Script------------------------------------------------------

set tabstop=4						" size of a hard tabstop
set shiftwidth=4					" size of an 'indent'
set softtabstop=4					" a combination of spaces and tabs
set shiftwidth=4					" size of an 'autoindent'
set number							" Line Numbers
set relativenumber					" Relative numbers
set showmatch						" Brackets
set scrolloff=2						" Min Visible Lines Around Cursor
set list                            " I wanna see tabs and trailing whitespaces
set path+=**						" Recursive env
set listchars=tab:→\ ,eol:\ ,trail:¬

filetype plugin on
syntax on

" Window manipulation: Resize window 
nnoremap + <C-W>+
nnoremap _ <C-W>-
nnoremap > <C-W>>
nnoremap < <C-W><

" Manipulate windows: Move between windows
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" Tweaks for browsing
let g:netrw_banner=0        " disable annoying banner
let g:netrw_browse_split=4  " open in prior window
let g:netrw_altv=1          " open splits to the right
let g:netrw_liststyle=3     " tree view
let g:netrw_list_hide=netrw_gitignore#Hide()
let g:netrw_list_hide.=',\(^\|\s\s\)\zs\.\S\+'

" Insert spaced tab TODO: Until I figure out how to do so
" imap <S-space> '    '

" Avoid launching vim with sudo, but make it less painful to edit config
cmap w!! w !sudo tee % >/dev/null<CR>

" Open underlying file in splits:
nmap <C-w>w :rightbelow wincmd f<CR>
nmap <C-w>e :rightbelow vertical wincmd f<CR>

nmap <ESC><C-u> :GundoToggle<CR>
nmap é :NERDTreeToggle<CR>
nmap àé :cclose<CR>
nmap àà :copen<CR>
nmap àN :cprevious<CR>
nmap àn :cnext<CR>
" Quick quit with confirm
nmap <ESC>q :qa

" Move between buffers
nmap <F1> :Unite buffer file file_rec/async file_mru -start-insert <CR>

" Unite
nmap <leader>b :Unite buffer -start-insert <CR>
nmap <leader>e :Unite file_mru file_rec/async -start-insert <CR>
nmap <leader>E :Unite file_mru -start-insert <CR>
nmap <leader>c :Unite change -start-insert <CR>
nmap <leader>j :Unite jump -auto-preview <CR>

" Incsearch
map /  <Plug>(incsearch-forward)
map ?  <Plug>(incsearch-backward)
map g/ <Plug>(incsearch-stay)

" folding
set foldmethod=marker
" show 80 columns delimiter
set colorcolumn=81
" support for 256 colors
set t_Co=256
" column color
hi ColorColumn ctermbg=235
" Enable Mouse Support
set mouse=a

" Execure the line under the cursor
vmap ! :!sh<CR>

colorscheme skittles_berry
