#!/usr/bin/env sh

alias ls='ls --color=auto'
alias l='ls -vCF'
alias ll='ls -valFh'
alias la='ls -vA'

alias df='df -h'

alias rlf='readlink -f'
alias fi.in='find . -iname '
alias fi.n='find . -name '

alias rf='readlink -f '
