"NeoBundle Scripts-----------------------------
if has('vim_starting')
  if &compatible
    set nocompatible               " Be iMproved
  endif

  " Required:
  set runtimepath+=~/.vim/bundle/neobundle.vim/
endif

" Required:
call neobundle#begin(expand('~/.vim/bundle'))

" Let NeoBundle manage NeoBundle
" Required:
NeoBundleFetch 'Shougo/neobundle.vim'

" Add or remove your Bundles here:
NeoBundle 'Shougo/neosnippet.vim'
NeoBundle 'Shougo/neosnippet-snippets'
NeoBundle 'tpope/vim-fugitive'
NeoBundle 'ctrlpvim/ctrlp.vim'
NeoBundle 'flazz/vim-colorschemes'
" NeoBundle 'dmonllao/vim-IDE'
NeoBundle 'scrooloose/nerdtree'
" NeoBundle 'fholgado/minibufexpl.vim'
" NeoBundle 'majutsushi/tagbar'
" NeoBundle 'hari-rangarajan/CCTree/'
" NeoBundle 'vim-scripts/exUtility'
" NeoBundle 'https://bitbucket.org/ns9tks/vim-autocomplpop/'
NeoBundle 'https://github.com/dfxyz/CandyPaper.vim'

"--Start My Packages ----------------------------

NeoBundle 'git://git.code.sf.net/p/vim-latex/vim-latex'

NeoBundle 'scrooloose/nerdtree'

"--End My Packages ------------------------------

" You can specify revision/branch/tag.
NeoBundle 'Shougo/vimshell', { 'rev' : '3787e5' }

" Required:
call neobundle#end()

" Required:
filetype plugin indent on

" If there are uninstalled bundles found on startup,
" this will conveniently prompt you to install them.
NeoBundleCheck
"End NeoBundle Scripts-------------------------

" size of a hard tabstop
set tabstop=4

" size of an "indent"
set shiftwidth=4

" a combination of spaces and tabs are used to simulate tab stops at a width
" other than the (hard)tabstop
set softtabstop=4

" Line Numbers
set number
set relativenumber

" vim Latex, set output format to pdf
let g:Tex_DefaultTargetFormat = 'pdf'
let g:Tex_MultipleCompileFormats='pdf, aux'
let g:Tex_ViewRule_pdf = "evince &>/dev/null"

autocmd InsertEnter * :set number
autocmd InsertLeave * :set relativenumber
