" Vim main configuration file
"
" (C) 2016 - Roosembert Palacios <roosembert.palacios@epfl.ch>
" Released under CC BY-NC-SA License: https://creativecommons.org/licenses/

" NeoBundle Scripts {{{
if has('vim_starting')
  if &compatible
    set nocompatible               " Be iMproved
  endif

  " Required:
  set runtimepath+=~/.vim/bundle/neobundle.vim/
endif

" Required:
call neobundle#begin(expand('~/.vim/bundle'))

" Let NeoBundle manage NeoBundle
" Required:
NeoBundleFetch 'Shougo/neobundle.vim'

" My Packages {{{
NeoBundle 'scrooloose/nerdtree'
NeoBundle 'Lokaltog/vim-easymotion'
NeoBundle 'vim-scripts/Align'
NeoBundle 'sjl/gundo.vim'
NeoBundle 'shawncplus/skittles_berry'
NeoBundle 'guyzmo/vim-etherpad'

NeoBundle 'shougo/vinarise'
NeoBundle 'tpope/vim-fugitive'
NeoBundle 'nathanaelkane/vim-indent-guides'
" NeoBundle 'Valloric/YouCompleteMe'
" NeoBundle 'powerline/powerline'
" NeoBundleLazy 'jeaye/color_coded'

" }}} My Packages --------------------------------------------------------------

" ???
set laststatus=2

" You can specify revision/branch/tag.
NeoBundle 'Shougo/vimshell', { 'rev' : '3787e5' }

" Required:
call neobundle#end()

" Required:
filetype plugin indent on

" If there are uninstalled bundles found on startup,
" this will conveniently prompt you to install them.
NeoBundleCheck
" }}} End NeoBundle Scripts---------------------------------------------------- 

set tabstop=4						" size of a hard tabstop
set shiftwidth=4					" size of an 'indent'
set softtabstop=4					" a combination of spaces and tabs
set shiftwidth=4					" size of an 'autoindent'
set number							" Line Numbers
set relativenumber					" Relative numbers
set showmatch						" Brackets
set scrolloff=2						" Min Visible Lines Around Cursor
set list                            " I wanna see tabs and trailing whitespaces
set listchars=tab:→\ ,eol:\ ,trail:¬

filetype plugin on
syntax on

" Window manipulation: Resize window 
nnoremap + <C-W>+
nnoremap _ <C-W>-
nnoremap > <C-W>>
nnoremap < <C-W><

" Manipulate windows: Move between windows
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" Insert spaced tab TODO: Until I figure out how to do so
" imap <S-space> '    '

" Avoid launching vim with sudo, but make it less painful to edit config
cmap w!! w !sudo tee % >/dev/null<CR>

" Souvenirs from my eclipse age... open underlying file in vsplit:
nmap <F3> :vertical wincmd f<CR>

nmap <ESC><C-u> :GundoToggle<CR>
nmap <ESC>é :NERDTreeToggle<CR>

" folding
set foldmethod=marker
" show 80 columns delimiter
set colorcolumn=81
" support for 256 colors
set t_Co=256
" column color
hi ColorColumn ctermbg=235
" Enable Mouse Support
set mouse=a

" Execure the line under the cursor
vmap ! :!sh<CR>

colorscheme skittles_berry
