#!/bin/sh
# Environment set when logging into a shell.
# Written by ayekat on a frustrating evening in september 2014.

# PATH is set in profile.

# Editor and pager:
export EDITOR="$(which vim)"
export VISUAL="$(which vim) -O"
export PAGER="$(which less) -j.3"

# Honor XDG LIB Home
export LD_LIBRARY_PATH="${XDG_LIB_HOME}:${LD_LIBRARY_PATH}"
