#!/bin/bash

[[ -z "$1" ]] && echo "Please specify device number to toggle" && exit -1

export Device="$1"

if [[ -z "$(xinput list-props "${Device}" | grep "Device Enabled" | grep 0)" ]]; then
	xinput disable "${Device}";
else
	xinput enable "${Device}";
fi

