# Source X config if it exists
xrdb $XDG_CONFIG_HOME/X11/Xresources

# Run sxhkd
pkill sxhkd
sxhkd &

# Custom Layout :D
kbcomp  -I$(readlink -f ~$XDG_CONFIG_HOME/xkb/) $(readlink -f ~$XDG_CONFIG_HOME/xkb/keymap/Systech13Defs-fr_CH) $DISPLAY

exec /usr/bin/bspwm -c ~$XDG_CONFIG_HOME/bspwm/bspwmrc
