#!/bin/bash

USERNAME="rpalacio"
FILES_Server="8"
sudo mount -t cifs //files${FILES_Server}.epfl.ch/data/${USERNAME} /mnt/remote/smbShares/epfl-files${FILES_Server}/ -o user=rpalacio@INTRANET,rw,noexec,uid=1000,gid=1000,noperm,forceuid,forcegid
