# The following lines were added by compinstall

zstyle ':completion:*' completer _expand _complete _ignored _correct _approximate _prefix
zstyle :compinstall filename '/home/roosemberth/.zshrc'

# This will allow "Special dirs" (./ and ../) to be available as autocomplete
zstyle ':completion:*' special-dirs true

# This pushes current cmd to a stack so I'll let me run something else and restores the cmd on the next shell prompt
bindkey "^B" push-input

autoload -Uz compinit
compinit
# End of lines added by compinstall

# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000000
SAVEHIST=1000000
setopt appendhistory beep notify
bindkey -v
# End of lines configured by zsh-newuser-install

# enable color support of ls and friends
alias ls='ls --color=auto'
#alias dir='dir --color=auto'
#alias vdir='vdir --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# quite handy!
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

export EDITOR="vim"

# This "marks" the terminal by exporting an non empty variable (so if we nest, we "mark" the nest")
alias MARK="MARK="yes" "
#bindkey "^M" 'MARK zsh'

# mixer alias
if [[ ! -z "$(whence pulsemixer)" ]]; then
	alias mixer="pulsemixer"
elif [[ ! -z "$(whence alsamixer)" ]]; then
	alias mixer="alsamixer"
fi

# This will fix broken (bash imported) scripts which use "for var in ${list of space separated variables goes here}" loops
setopt sh_word_split

# Check if we're in a nested shell, and add to PS1
if [[ "$(ps hp $PPID -o comm)" == "$0" ]]; then 
	if [[ -z "$MARK" ]]; then
		export PS1="-${PS1}"
	else 
		export PS1="|${PS1}"
		export MARK=""
	fi
fi

# "Include" custom shell functions. They need to have a proper function declaration
# ej. --------------------------------------------------------
# function myfunc(){
#	# cool function code here
# }
# ----------------- file: ~/dotfiles/zsh/functions/myfunc.func
# This functions can be located in subdirectories too, but only the files ending 
# with '.func' will be included. 

ADDITIONAL_FUNCTIONS=$(find ~/dotfiles/zsh/functions -type f -iname "*.func")

for newFunction in ${ADDITIONAL_FUNCTIONS}; do
	source ${newFunction}
	if [[ $? != 0 ]]; then
		echo "Error processing additional function ${newFunction}"
	fi
done

unset ADDITIONAL_FUNCTIONS

# Space for small functions which do not merite to be in a single file ----------
function reload(){
	source ~/.zshrc
}

function whoIsMyParent(){
	# Grep is just for coloring...
	ps hu $PPID | grep $PPID
}

function aps(){
	ps aux | grep -v grep | grep -i $1
}

function lastCommand(){
	history | tail -n 1 | sed 's/[ 0-9]*//'
}

# -------------------------------------------------------------------------------

# This will load local "Host-dependant" zsh config files, so we won't polute git repo :)
if [[ -e ~/.zshrc.local ]]; then
	source ~/.zshrc.local
fi

if [[ -e ${HOME}/.gem/ruby/2.2.0/bin ]]; then
	export PATH="${HOME}/.gem/ruby/2.2.0/bin:$PATH"

	if [[ -e ${HOME}/.gem/ruby/2.2.0/gems/tmuxinator-0.6.11/completion/tmuxinator.zsh ]]; then
		source ${HOME}/.gem/ruby/2.2.0/gems/tmuxinator-0.6.11/completion/tmuxinator.zsh
	fi

fi

